import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '../styles/global.scss'
import "../styles/index.scss"


import "../styles/global.scss";
import "aos/dist/aos.css";
import "../styles/index.scss";
import { ToastContainer } from "react-toastify";
// import { app } from "@/lib/firebase/config"; 
import StoreProvider from "./StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // app 
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ToastContainer />
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
